# Generated by Django 2.1.2 on 2018-10-30 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('coursename', models.CharField(max_length=50)),
                ('courseid', models.IntegerField(default=5, primary_key=True, serialize=False)),
                ('coursefee', models.IntegerField(default=5)),
                ('courseduration', models.IntegerField(default=3)),
            ],
        ),
    ]
