# Generated by Django 2.1.2 on 2018-10-31 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20181030_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('name', models.CharField(max_length=40)),
                ('contect', models.IntegerField(default=10, primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=6)),
                ('username', models.CharField(max_length=40)),
                ('password', models.IntegerField(default=10)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
