# Generated by Django 2.1.2 on 2018-11-01 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='faculty',
            fields=[
                ('id', models.IntegerField(default=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('cno', models.EmailField(default=10, max_length=254)),
                ('gender', models.CharField(max_length=5)),
                ('username', models.CharField(max_length=40)),
                ('password', models.IntegerField(default=20)),
                ('email', models.EmailField(max_length=254)),
                ('course', models.CharField(max_length=10)),
            ],
        ),
    ]
