# Generated by Django 2.1.2 on 2018-11-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_faculty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='cno',
        ),
        migrations.AddField(
            model_name='faculty',
            name='contact',
            field=models.IntegerField(default=10),
        ),
    ]
